spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: authorization-microservice
              uri: lb://AUTHORIZATION-MICROSERVICE
              predicates:
                - Path=/oauth2/**

            - id: users-microservice
              uri: lb://USERS-MICROSERVICE
              predicates:
                - Path=/user/**

            - id: messages-microservice-channels
              uri: lb://MESSAGES-MICROSERVICE
              predicates:
                - Path=/channel**

            - id: messages-microservice-messages
              uri: lb://MESSAGES-MICROSERVICE
              predicates:
                - Path=/message**
server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetchRegistry: true