spring:
  application:
    name: authorization-microservice

  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres_db
    username: postgres_user
    password: password

  kafka:
    producer:
      bootstrap-servers: localhost:9092

server:
  port: ${PORT:0}

logging:
  level:
    root: ${LOG_LEVEL:INFO}
    com.wannaverse: ${LOG_LEVEL:TRACE}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetchRegistry: true
