[versions]
springCloudVersion = "2025.1.0"
slf4j = "2.0.16"
jackson = "3.0.3"
spotless = "8.1.0"

[libraries]
spring-cloud-bom = { group = "org.springframework.cloud", name = "spring-cloud-dependencies", version.ref="springCloudVersion" }
spring-log4j2 = { group = "org.springframework.boot", name = "spring-boot-starter-log4j2" }
slf4j-bom = { group = "org.slf4j", name = "slf4j-bom", version.ref = "slf4j" }
jackson-bom = { group = "tools.jackson", name = "jackson-bom", version.ref = "jackson" }
jackson-core = { group = "tools.jackson", name = "jackson-core" }
jackson-databind = { group = "tools.jackson", name = "jackson-databind" }
jackson-annotations = { group = "com.fasterxml.jackson.core", name = "jackson-annotations" }

[bundles]
jackson = ["jackson-annotations", "jackson-core", "jackson-databind"]

[plugins]
java = { id = "java" }
spotless = { id = "com.diffplug.gradle.spotless", version.ref = "spotless" }
